web_app_tsu/abobus/urls.py
from django.contrib import admin
from django.urls import path
from django.http import HttpResponse
from django.db import connection
from .views import *

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index, name='index'),
    path('projects/', projects, name='projects'),
    path('add_project/', add_project, name='add_project'),
    path('tables/', tables, name='tables'),
    path('register/', register, name='register'),
    path('personal_cabinet/', personal_cabinet, name='personal_cabinet'),
    path('create_project/', create_project_view, name='create_project'),
    path('login', login_view, name = 'login'),
]

web_app_tsu/web_app_tsu/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

web_app_tsu/abobus/models.py
from django.db import models
from django.contrib.auth.models import User, Group


class Profile(models.Model):
    USER_TYPE_CHOICES = [
        ('STUDENT', 'Student'),
        ('INVESTOR', 'Investor'),
    ]
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    user_type = models.CharField(max_length=10, choices=USER_TYPE_CHOICES, null=True)
    name = models.CharField(max_length=50, null=True)
    last_name = models.CharField(max_length=50, null=True)

    def __str__(self):
        return f'{self.user.username} ({self.user_type})'

class Project(models.Model):
    title = models.CharField(max_length=200)
    description = models.TextField()
    payback_period = models.PositiveIntegerField()
    goals = models.TextField()
    intended_outcome = models.TextField()
    created_by = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.title
    
class Investment(models.Model):
    amount = models.DecimalField(max_digits=10, decimal_places=2)
    investment_date = models.DateField(auto_now_add=True)
    investor = models.ForeignKey(Profile, on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.investment_date} - {self.amount}'

web_app_tsu/abobus/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.models import User
from .models import Project
from django import forms
from django.contrib.auth.forms import UserCreationForm
from .models import Profile

class RegistrationForm(UserCreationForm):
    USER_TYPE_CHOICES = [
        ('STUDENT', 'Student'),
        ('INVESTOR', 'Investor'),
    ]
    user_type = forms.ChoiceField(choices=USER_TYPE_CHOICES, widget=forms.RadioSelect)
    name = forms.CharField(max_length=50)
    last_name = forms.CharField(max_length=50)

    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2', 'user_type', 'name', 'last_name')

    def save(self, commit=True):
        user = super(RegistrationForm, self).save(commit=False)
        user.save()
        profile = Profile.objects.create(user=user, user_type=self.cleaned_data['user_type'],
                                          name=self.cleaned_data['name'], last_name=self.cleaned_data['last_name'])
        if commit:
            profile.save()
        return user

class LoginForm(AuthenticationForm):
    username = forms.CharField(label='Username', widget=forms.TextInput(attrs={'class': 'form-control'}))
    password = forms.CharField(label='Password', widget=forms.PasswordInput(attrs={'class': 'form-control'}))

class ProjectForm(forms.ModelForm):
    class Meta:
        model = Project
        fields = ['title', 'description', 'payback_period', 'goals', 'intended_outcome']

web_app_tsu/abobus/views.py
from django.shortcuts import render, redirect, HttpResponse
from django.contrib.auth import authenticate, login
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User, Group
from django.db.models.signals import post_save
from django.dispatch import receiver
from .models import Project, User, Profile
from .forms import ProjectForm, RegistrationForm, LoginForm
from django.db import connection
from django.contrib import messages

def index(request):
    return HttpResponse("Hello")
def projects(request):
    response = HttpResponse(f"<h1>Проекты</h1>")
    return response
def add_project(request):
    response = HttpResponse(f"<h1>Добавить проект</h1>")
    return response
def tables(request):
    cursor = connection.cursor()
    table_list = connection.introspection.get_table_list(cursor)
    return HttpResponse(table_list)

def register(request):
    if request.method == 'POST':
        form = RegistrationForm(request.POST)
        if form.is_valid():
            user = form.save()
            user_type = form.cleaned_data['user_type']
            name = form.cleaned_data['name']
            last_name = form.cleaned_data['last_name']
            profile = user.profile
            profile.user_type = user_type
            profile.name = name
            profile.last_name = last_name
            profile.save()
            if user_type == 'STUDENT':
                student_group = Group.objects.get(name='Студенты')
                student_group.user_set.add(user)
            elif user_type == 'INVESTOR':
                investor_group = Group.objects.get(name='Инвесторы')
                investor_group.user_set.add(user)
            return redirect('login')
    else:
        form = RegistrationForm()
    return render(request, 'registration.html', {'form': form})

@login_required
def personal_cabinet(request):
    username = request.user.username
    projects = Project.objects.filter(created_by=request.user)
    return render(request, 'personal_cabinet.html', {'username': username, 'projects': projects})

@login_required
def create_project_view(request):
    if request.method == 'POST':
        form = ProjectForm(request.POST)
        if form.is_valid():
            project = form.save(commit=False)
            project.created_by = request.user
            project.save()
            messages.success(request, 'Project created successfully!')
            return redirect('personal_cabinet')
    else:
        form = ProjectForm()
    return render(request, 'create_project.html', {'form': form})

# @receiver(post_save, sender=User)
# def create_profile(sender, instance, created, **kwargs):
#     if created:
#         user_type = instance.profile.user_type
#         if user_type == 'STUDENT':
#             Student.objects.create(user=instance)
#         elif user_type == 'INVESTOR':
#             Investor.objects.create(user=instance)


def login_view(request):
    if request.method == 'POST':
        form = LoginForm(request=request, data=request.POST)
        if form.is_valid():
            # Получаем email и пароль из формы
            email = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            # Аутентифицируем пользователя
            user = authenticate(request, username=email, password=password)
            if user is not None:
                # Устанавливаем сессию и редиректим на нужную страницу
                login(request, user)
                if user.profile.user_type == 'INVESTOR':
                    return redirect('investor_cabinet')
                else:
                    return redirect('personal_cabinet')
    else:
        form = LoginForm()
    return render(request, 'login.html', {'form': form})


# @login_required
# def investor_cabinet(request):
    # order_by = request.GET.get('order_by', 'title')
    # projects = Project.objects.order_by(order_by)
    # return render(request, 'investor_cabinet.html', {'projects': projects})
@login_required
def investor_cabinet(request):
    sort_by = request.GET.get('sort_by', 'title')
    projects = Project.objects.all().order_by(sort_by)
    context = {'projects': projects}
    return render(request, 'investor_cabinet.html', context)

web_app_tsu/abobus/templates/base.html
<!DOCTYPE html>
<html>
<head>
    <title>{% block title %}{% endblock %}</title>
    <!-- Подключение стилей Material Design Lite -->
    <link rel="stylesheet" href="https://code.getmdl.io/1.3.0/material.indigo-pink.min.css">
    <!-- Подключение библиотеки Material Design Lite -->
    <script defer src="https://code.getmdl.io/1.3.0/material.min.js"></script>
    <!-- Подключение иконок Material Design Icons -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
    <!-- Подключение вашего файла со стилями -->
    <link rel="stylesheet" href="{% block css %}{% endblock %}">
</head>
<body>
    {% block content %}
    {% endblock %}
</body>
</html>

web_app_tsu/abobus/templates/create_project.html
<!DOCTYPE html>
<html>
<head>
	<title>Создание проекта</title>
</head>
<body>
	<h1>Создание проекта</h1>
	<form method="post">
		{% csrf_token %}
		<label for="id_title">Название:</label>
		<input type="text" name="title" id="id_title"><br><br>

		<label for="id_description">Описание:</label>
		<textarea name="description" id="id_description"></textarea><br><br>

		<label for="id_payback_period">Срок окупаемости:</label>
		<input type="number" name="payback_period" id="id_payback_period"><br><br>

		<label for="id_goals">Цели:</label>
		<textarea name="goals" id="id_goals"></textarea><br><br>

		<label for="id_intended_outcome">Ожидаемый результат:</label>
		<textarea name="intended_outcome" id="id_intended_outcome"></textarea><br><br>

		<input type="submit" value="Создать проект">
	</form>
</body>
</html>

web_app_tsu/abobus/templates/investor_cabinet.html
<!DOCTYPE html>
<html>
<head>
  <title>Личный кабинет инвестора</title>
  <!-- Подключаем Materialize CSS -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
  <!-- Подключаем наш CSS файл -->
  <link rel="stylesheet" href="styles.css">
</head>
<body>
  <!-- Шапка страницы -->
  <nav>
    <div class="nav-wrapper blue">
      <a href="#" class="brand-logo center">Личный кабинет инвестора</a>
    </div>
  </nav>
  
  <form class="col s12" method="get">
    <div class="input-field col s4">
      <select name="sort_by">
        <option value="title">Сортировать по названию</option>
        <option value="description">Сортировать по описанию</option>
        <option value="payback_period">Сортировать по периоду окупаемости</option>
        <option value="goals">Сортировать по целям проекта</option>
        <option value="intended_outcome">Сортировать по предполагаемому результату</option>
      </select>
      <label>Сортировка</label>
    </div>
    <div class="input-field col s2">
      <button class="btn waves-effect waves-light blue" type="submit">Сортировать</button>
    </div>
  </form>
  
    
    <!-- Список проектов -->
    <ul class="collection">
      {% for project in projects %}
      <li class="collection-item">
        <div>
          <h5>{{ project.title }}</h5>
          <p>{{ project.description }}</p>
          <p>Период окупаемости: {{ project.payback_period }}</p>
          <p>Цели проекта: {{ project.goals }}</p>
          <p>Предполагаемый результат: {{ project.intended_outcome }}</p>
        </div>
      </li>
      {% endfor %}
    </ul>
  </div>
  
  <!-- Подключаем Materialize JS -->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
  <!-- Инициализируем select и другие элементы -->
  <script>
    document.addEventListener('DOMContentLoaded', function() {
      var elems = document.querySelectorAll('select');
      var instances = M.FormSelect.init(elems);
      var elems2 = document.querySelectorAll('.datepicker');
      var instances2 = M.Datepicker.init(elems2);
    });
  </script>
  <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
  <script>
    $(document).ready(function() {
  $('select[name="sort_by"]').on('change', function() {
    var sort_by = $(this).val();
    if (sort_by) {
      window.location.href = window.location.pathname + '?sort_by=' + sort_by;
    }
  });
  });
  </script>
  
</body>
</html>

web_app_tsu/abobus/templates/login.html
{% extends 'base.html' %}

{% block main %}
    {% block content %}
        <h1>Login</h1>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Log in</button>
        </form>
    {% endblock %}
{% endblock %}

web_app_tsu/abobus/templates/login_abobus.html
<!DOCTYPE html>
<html>
  <head>
    <title>Вход</title>
  </head>
  <body>
    <h1>Вход</h1>
    <form action="{% url 'login' %}" method="post">
      {% csrf_token %}
      <label for="email">Электронная почта:</label>
      <input type="email" id="email" name="email" required><br><br>
      <label for="password">Пароль:</label>
      <input type="password" id="password" name="password" required><br><br>
      <button type="submit">Войти</button>
    </form>
  </body>
</html>

web_app_tsu/abobus/templates/personal_cabinet.html
<!DOCTYPE html>
<html>
<head>
	<title>Личный кабинет {{request.user.username}}</title>
</head>
<body>
	<h1>Личный кабинет {{request.user.username}}</h1>
    <a href="{% url 'create_project' %}">Создать проект</a>
	<h2>Список ваших проектов:</h2>
	<ul>
	{% for project in projects %}
		<li>{{ project.title }} - {{ project.description }} - {{ project.payback_period }} - {{ project.goals }} - {{ project.intended_outcome }}</li>
	{% endfor %}
	</ul>
</body>
</html>

web_app_tsu/abobus/templates/registration.html
{% extends 'base.html' %}

{% block content %}
  <h2>Регистрация</h2>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Зарегистрироваться</button>
  </form>
{% endblock %}

web_app_tsu/abobus/templates/registration_abobus.html
<!DOCTYPE html>
<html>
<head>
  <title>Регистрация</title>
</head>
<body>
  <h1>Регистрация</h1>
  <form method="post">
    {% csrf_token %}
    <label for="name">Имя:</label>
    <input type="text" id="name" name="name"><br><br>
    <label for="lastname">Фамилия:</label>
    <input type="text" id="lastname" name="lastname"><br><br>
    <label for="name">email:</label>
    <input type="text" id="email" name="email"><br><br>
    <label for="role">Роль:</label>
    <input type="radio" id="role_student" name="role" value="student" checked>
    <label for="role_student">Студент</label>
    <input type="radio" id="role_investor" name="role" value="investor">
    <label for="role_investor">Инвестор</label><br><br>
    <label for="password">Пароль:</label>
    <input type="password" id="password" name="password"><br><br>
    <label for="password_confirm">Повторите пароль:</label>
    <input type="password" id="password_confirm" name="password_confirm"><br><br>
    <input type="submit" value="Зарегистрироваться">
  </form>
</body>
</html>

web_app_tsu/abobus/templates/student_list.html
<!DOCTYPE html>
<html>
<head>
  <title>Список студентов</title>
</head>
<body>
  <h1>Список студентов</h1>
  <table>
    <thead>
      <tr>
        <th>Имя</th>
        <th>Фамилия</th>
        <th>Email</th>
      </tr>
    </thead>
    <tbody>
      {% for student in students %}
      <tr>
        <td>{{ student.name }}</td>
        <td>{{ student.lastname }}</td>
        <td>{{ student.email }}</td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
</body>
</html>